// AUTO-GENERATED by scripts/gen-cards.mjs — do not edit by hand.
// Source: the real artwork files in public/robots/ (98 images).
// 26 cards include the official vibe/vibe descriptions (verified 2026-09-28).
// Rarity distribution is seeded-deterministic; tune it in scripts/gen-cards.mjs.
import type { RobotCard } from './types';

export const CARDS: RobotCard[] = [
  {
    "id": "001",
    "number": 1,
    "file": "vibe-vibers-agent-34.png",
    "image": "/robots/vibe-vibers-agent-34.png",
    "name": "AGENTS 34",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 48,
      "speed": 87,
      "spark": 68
    },
    "source": "file-derived"
  },
  {
    "id": "002",
    "number": 2,
    "file": "vibe-vibers-agent-37.png",
    "image": "/robots/vibe-vibers-agent-37.png",
    "name": "AGENTS 37",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 79,
      "speed": 30,
      "spark": 88
    },
    "source": "file-derived"
  },
  {
    "id": "003",
    "number": 3,
    "file": "vibe-vibers-agent-48.png",
    "image": "/robots/vibe-vibers-agent-48.png",
    "name": "AGENTS 48",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 30,
      "speed": 37,
      "spark": 58
    },
    "source": "file-derived"
  },
  {
    "id": "004",
    "number": 4,
    "file": "vibe-vibers-agent-49.png",
    "image": "/robots/vibe-vibers-agent-49.png",
    "name": "AGENTS 49",
    "description": null,
    "series": "AGENTS",
    "rarity": "epic",
    "stats": {
      "power": 77,
      "speed": 55,
      "spark": 34
    },
    "source": "file-derived"
  },
  {
    "id": "005",
    "number": 5,
    "file": "vibe-vibers-agent-52.png",
    "image": "/robots/vibe-vibers-agent-52.png",
    "name": "AGENTS 52",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 54,
      "speed": 81,
      "spark": 47
    },
    "source": "file-derived"
  },
  {
    "id": "006",
    "number": 6,
    "file": "vibe-vibers-agent-55.png",
    "image": "/robots/vibe-vibers-agent-55.png",
    "name": "AGENTS 55",
    "description": null,
    "series": "AGENTS",
    "rarity": "legendary",
    "stats": {
      "power": 43,
      "speed": 62,
      "spark": 84
    },
    "source": "file-derived"
  },
  {
    "id": "007",
    "number": 7,
    "file": "vibe-vibers-agent-56.png",
    "image": "/robots/vibe-vibers-agent-56.png",
    "name": "AGENTS 56",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 64,
      "speed": 49,
      "spark": 69
    },
    "source": "file-derived"
  },
  {
    "id": "008",
    "number": 8,
    "file": "vibe-vibers-agent-57.png",
    "image": "/robots/vibe-vibers-agent-57.png",
    "name": "AGENTS 57",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 84,
      "speed": 57,
      "spark": 84
    },
    "source": "file-derived"
  },
  {
    "id": "009",
    "number": 9,
    "file": "vibe-vibers-agent-60.png",
    "image": "/robots/vibe-vibers-agent-60.png",
    "name": "AGENTS 60",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 98,
      "speed": 66,
      "spark": 48
    },
    "source": "file-derived"
  },
  {
    "id": "010",
    "number": 10,
    "file": "vibe-vibers-agent-63.png",
    "image": "/robots/vibe-vibers-agent-63.png",
    "name": "AGENTS 63",
    "description": null,
    "series": "AGENTS",
    "rarity": "uncommon",
    "stats": {
      "power": 98,
      "speed": 44,
      "spark": 62
    },
    "source": "file-derived"
  },
  {
    "id": "011",
    "number": 11,
    "file": "vibe-vibers-agent-64.png",
    "image": "/robots/vibe-vibers-agent-64.png",
    "name": "AGENTS 64",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 78,
      "speed": 57,
      "spark": 51
    },
    "source": "file-derived"
  },
  {
    "id": "012",
    "number": 12,
    "file": "vibe-vibers-agent-67.png",
    "image": "/robots/vibe-vibers-agent-67.png",
    "name": "AGENTS 67",
    "description": null,
    "series": "AGENTS",
    "rarity": "uncommon",
    "stats": {
      "power": 47,
      "speed": 79,
      "spark": 57
    },
    "source": "file-derived"
  },
  {
    "id": "013",
    "number": 13,
    "file": "vibe-vibers-agent-68.png",
    "image": "/robots/vibe-vibers-agent-68.png",
    "name": "AGENTS 68",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 94,
      "speed": 43,
      "spark": 87
    },
    "source": "file-derived"
  },
  {
    "id": "014",
    "number": 14,
    "file": "vibe-vibers-agent-69.png",
    "image": "/robots/vibe-vibers-agent-69.png",
    "name": "AGENTS 69",
    "description": null,
    "series": "AGENTS",
    "rarity": "uncommon",
    "stats": {
      "power": 64,
      "speed": 72,
      "spark": 79
    },
    "source": "file-derived"
  },
  {
    "id": "015",
    "number": 15,
    "file": "vibe-vibers-agent-71.png",
    "image": "/robots/vibe-vibers-agent-71.png",
    "name": "AGENTS 71",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 83,
      "speed": 49,
      "spark": 72
    },
    "source": "file-derived"
  },
  {
    "id": "016",
    "number": 16,
    "file": "vibe-vibers-agent-84.png",
    "image": "/robots/vibe-vibers-agent-84.png",
    "name": "AGENTS 84",
    "description": null,
    "series": "AGENTS",
    "rarity": "uncommon",
    "stats": {
      "power": 84,
      "speed": 62,
      "spark": 41
    },
    "source": "file-derived"
  },
  {
    "id": "017",
    "number": 17,
    "file": "vibe-vibers-agent-85.png",
    "image": "/robots/vibe-vibers-agent-85.png",
    "name": "AGENTS 85",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 31,
      "speed": 75,
      "spark": 100
    },
    "source": "file-derived"
  },
  {
    "id": "018",
    "number": 18,
    "file": "vibe-vibers-agent-96.png",
    "image": "/robots/vibe-vibers-agent-96.png",
    "name": "AGENTS 96",
    "description": null,
    "series": "AGENTS",
    "rarity": "epic",
    "stats": {
      "power": 68,
      "speed": 51,
      "spark": 81
    },
    "source": "file-derived"
  },
  {
    "id": "019",
    "number": 19,
    "file": "vibe-vibers-agent-103.png",
    "image": "/robots/vibe-vibers-agent-103.png",
    "name": "AGENTS 103",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 88,
      "speed": 65,
      "spark": 79
    },
    "source": "file-derived"
  },
  {
    "id": "020",
    "number": 20,
    "file": "vibe-vibers-agent-107.png",
    "image": "/robots/vibe-vibers-agent-107.png",
    "name": "AGENTS 107",
    "description": null,
    "series": "AGENTS",
    "rarity": "uncommon",
    "stats": {
      "power": 48,
      "speed": 82,
      "spark": 73
    },
    "source": "file-derived"
  },
  {
    "id": "021",
    "number": 21,
    "file": "vibe-vibers-agent-111.png",
    "image": "/robots/vibe-vibers-agent-111.png",
    "name": "AGENTS 111",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 84,
      "speed": 40,
      "spark": 82
    },
    "source": "file-derived"
  },
  {
    "id": "022",
    "number": 22,
    "file": "vibe-vibers-agent-116.png",
    "image": "/robots/vibe-vibers-agent-116.png",
    "name": "AGENTS 116",
    "description": null,
    "series": "AGENTS",
    "rarity": "rare",
    "stats": {
      "power": 36,
      "speed": 49,
      "spark": 74
    },
    "source": "file-derived"
  },
  {
    "id": "023",
    "number": 23,
    "file": "vibe-vibers-agent-120.png",
    "image": "/robots/vibe-vibers-agent-120.png",
    "name": "AGENTS 120",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 56,
      "speed": 53,
      "spark": 90
    },
    "source": "file-derived"
  },
  {
    "id": "024",
    "number": 24,
    "file": "vibe-vibers-agent-123.png",
    "image": "/robots/vibe-vibers-agent-123.png",
    "name": "AGENTS 123",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 34,
      "speed": 85,
      "spark": 32
    },
    "source": "file-derived"
  },
  {
    "id": "025",
    "number": 25,
    "file": "vibe-vibers-agent-124.png",
    "image": "/robots/vibe-vibers-agent-124.png",
    "name": "AGENTS 124",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 70,
      "speed": 69,
      "spark": 80
    },
    "source": "file-derived"
  },
  {
    "id": "026",
    "number": 26,
    "file": "vibe-vibers-agent-141.png",
    "image": "/robots/vibe-vibers-agent-141.png",
    "name": "AGENTS 141",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 30,
      "speed": 100,
      "spark": 89
    },
    "source": "file-derived"
  },
  {
    "id": "027",
    "number": 27,
    "file": "vibe-vibers-agent-142.png",
    "image": "/robots/vibe-vibers-agent-142.png",
    "name": "AGENTS 142",
    "description": null,
    "series": "AGENTS",
    "rarity": "common",
    "stats": {
      "power": 43,
      "speed": 70,
      "spark": 86
    },
    "source": "file-derived"
  },
  {
    "id": "028",
    "number": 28,
    "file": "vibe-vibers-bureau-4.png",
    "image": "/robots/vibe-vibers-bureau-4.png",
    "name": "BUREAU 04",
    "description": "Cream Viber with a white fedora and blue glasses",
    "series": "BUREAU",
    "rarity": "rare",
    "stats": {
      "power": 96,
      "speed": 39,
      "spark": 35
    },
    "source": "official:vibevibe"
  },
  {
    "id": "029",
    "number": 29,
    "file": "vibe-vibers-bureau-8.png",
    "image": "/robots/vibe-vibers-bureau-8.png",
    "name": "BUREAU 08",
    "description": "Purple Viber with blue eyes and long black arms",
    "series": "BUREAU",
    "rarity": "common",
    "stats": {
      "power": 59,
      "speed": 79,
      "spark": 65
    },
    "source": "official:vibevibe"
  },
  {
    "id": "030",
    "number": 30,
    "file": "vibe-vibers-bureau-23.png",
    "image": "/robots/vibe-vibers-bureau-23.png",
    "name": "BUREAU 23",
    "description": "Yellow Viber with a black cap and cream face bands",
    "series": "BUREAU",
    "rarity": "uncommon",
    "stats": {
      "power": 91,
      "speed": 58,
      "spark": 61
    },
    "source": "official:vibevibe"
  },
  {
    "id": "031",
    "number": 31,
    "file": "vibe-vibers-bureau-24.png",
    "image": "/robots/vibe-vibers-bureau-24.png",
    "name": "BUREAU 24",
    "description": "Orange Viber with a black visor and wide boots",
    "series": "BUREAU",
    "rarity": "common",
    "stats": {
      "power": 35,
      "speed": 33,
      "spark": 90
    },
    "source": "official:vibevibe"
  },
  {
    "id": "032",
    "number": 32,
    "file": "vibe-vibers-bureau-25.png",
    "image": "/robots/vibe-vibers-bureau-25.png",
    "name": "BUREAU 25",
    "description": "Charcoal Viber with a cream fedora and mint glasses",
    "series": "BUREAU",
    "rarity": "uncommon",
    "stats": {
      "power": 55,
      "speed": 81,
      "spark": 95
    },
    "source": "official:vibevibe"
  },
  {
    "id": "033",
    "number": 33,
    "file": "vibe-vibers-bureau-31.png",
    "image": "/robots/vibe-vibers-bureau-31.png",
    "name": "BUREAU 31",
    "description": "Turquoise Viber with glowing lime bars and a single antenna",
    "series": "BUREAU",
    "rarity": "common",
    "stats": {
      "power": 82,
      "speed": 86,
      "spark": 93
    },
    "source": "official:vibevibe"
  },
  {
    "id": "034",
    "number": 34,
    "file": "vibe-vibers-bureau-roll-1-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-1-3.png",
    "name": "BUREAU 1-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 53,
      "speed": 32,
      "spark": 89
    },
    "source": "file-derived"
  },
  {
    "id": "035",
    "number": 35,
    "file": "vibe-vibers-bureau-roll-1-7.png",
    "image": "/robots/vibe-vibers-bureau-roll-1-7.png",
    "name": "BUREAU 1-7",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 72,
      "speed": 88,
      "spark": 44
    },
    "source": "file-derived"
  },
  {
    "id": "036",
    "number": 36,
    "file": "vibe-vibers-bureau-roll-4-8.png",
    "image": "/robots/vibe-vibers-bureau-roll-4-8.png",
    "name": "BUREAU 4-8",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "rare",
    "stats": {
      "power": 100,
      "speed": 55,
      "spark": 31
    },
    "source": "file-derived"
  },
  {
    "id": "037",
    "number": 37,
    "file": "vibe-vibers-bureau-roll-5-2.png",
    "image": "/robots/vibe-vibers-bureau-roll-5-2.png",
    "name": "BUREAU 5-2",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 68,
      "speed": 52,
      "spark": 63
    },
    "source": "file-derived"
  },
  {
    "id": "038",
    "number": 38,
    "file": "vibe-vibers-bureau-roll-7-11.png",
    "image": "/robots/vibe-vibers-bureau-roll-7-11.png",
    "name": "BUREAU 7-11",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "epic",
    "stats": {
      "power": 53,
      "speed": 41,
      "spark": 64
    },
    "source": "file-derived"
  },
  {
    "id": "039",
    "number": 39,
    "file": "vibe-vibers-bureau-roll-8-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-8-3.png",
    "name": "BUREAU 8-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 80,
      "speed": 40,
      "spark": 70
    },
    "source": "file-derived"
  },
  {
    "id": "040",
    "number": 40,
    "file": "vibe-vibers-bureau-roll-8-10.png",
    "image": "/robots/vibe-vibers-bureau-roll-8-10.png",
    "name": "BUREAU 8-10",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 65,
      "speed": 89,
      "spark": 77
    },
    "source": "file-derived"
  },
  {
    "id": "041",
    "number": 41,
    "file": "vibe-vibers-bureau-roll-9-5.png",
    "image": "/robots/vibe-vibers-bureau-roll-9-5.png",
    "name": "BUREAU 9-5",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 73,
      "speed": 45,
      "spark": 35
    },
    "source": "file-derived"
  },
  {
    "id": "042",
    "number": 42,
    "file": "vibe-vibers-bureau-roll-15-4.png",
    "image": "/robots/vibe-vibers-bureau-roll-15-4.png",
    "name": "BUREAU 15-4",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 100,
      "speed": 61,
      "spark": 68
    },
    "source": "file-derived"
  },
  {
    "id": "043",
    "number": 43,
    "file": "vibe-vibers-bureau-roll-18-1.png",
    "image": "/robots/vibe-vibers-bureau-roll-18-1.png",
    "name": "BUREAU 18-1",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 77,
      "speed": 91,
      "spark": 78
    },
    "source": "file-derived"
  },
  {
    "id": "044",
    "number": 44,
    "file": "vibe-vibers-bureau-roll-18-2.png",
    "image": "/robots/vibe-vibers-bureau-roll-18-2.png",
    "name": "BUREAU 18-2",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "rare",
    "stats": {
      "power": 48,
      "speed": 85,
      "spark": 53
    },
    "source": "file-derived"
  },
  {
    "id": "045",
    "number": 45,
    "file": "vibe-vibers-bureau-roll-21-5.png",
    "image": "/robots/vibe-vibers-bureau-roll-21-5.png",
    "name": "BUREAU 21-5",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "epic",
    "stats": {
      "power": 96,
      "speed": 83,
      "spark": 97
    },
    "source": "file-derived"
  },
  {
    "id": "046",
    "number": 46,
    "file": "vibe-vibers-bureau-roll-21.png",
    "image": "/robots/vibe-vibers-bureau-roll-21.png",
    "name": "BUREAU 21",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 97,
      "speed": 65,
      "spark": 45
    },
    "source": "file-derived"
  },
  {
    "id": "047",
    "number": 47,
    "file": "vibe-vibers-bureau-roll-22-11.png",
    "image": "/robots/vibe-vibers-bureau-roll-22-11.png",
    "name": "BUREAU 22-11",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 55,
      "speed": 93,
      "spark": 78
    },
    "source": "file-derived"
  },
  {
    "id": "048",
    "number": 48,
    "file": "vibe-vibers-bureau-roll-22-12.png",
    "image": "/robots/vibe-vibers-bureau-roll-22-12.png",
    "name": "BUREAU 22-12",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 40,
      "speed": 75,
      "spark": 92
    },
    "source": "file-derived"
  },
  {
    "id": "049",
    "number": 49,
    "file": "vibe-vibers-bureau-roll-25-7.png",
    "image": "/robots/vibe-vibers-bureau-roll-25-7.png",
    "name": "BUREAU 25-7",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 50,
      "speed": 33,
      "spark": 79
    },
    "source": "file-derived"
  },
  {
    "id": "050",
    "number": 50,
    "file": "vibe-vibers-bureau-roll-26-1.png",
    "image": "/robots/vibe-vibers-bureau-roll-26-1.png",
    "name": "BUREAU 26-1",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 37,
      "speed": 99,
      "spark": 62
    },
    "source": "file-derived"
  },
  {
    "id": "051",
    "number": 51,
    "file": "vibe-vibers-bureau-roll-28-2.png",
    "image": "/robots/vibe-vibers-bureau-roll-28-2.png",
    "name": "BUREAU 28-2",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 57,
      "speed": 87,
      "spark": 100
    },
    "source": "file-derived"
  },
  {
    "id": "052",
    "number": 52,
    "file": "vibe-vibers-bureau-roll-29-4.png",
    "image": "/robots/vibe-vibers-bureau-roll-29-4.png",
    "name": "BUREAU 29-4",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 89,
      "speed": 99,
      "spark": 54
    },
    "source": "file-derived"
  },
  {
    "id": "053",
    "number": 53,
    "file": "vibe-vibers-bureau-roll-29.png",
    "image": "/robots/vibe-vibers-bureau-roll-29.png",
    "name": "BUREAU 29",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "epic",
    "stats": {
      "power": 39,
      "speed": 48,
      "spark": 42
    },
    "source": "file-derived"
  },
  {
    "id": "054",
    "number": 54,
    "file": "vibe-vibers-bureau-roll-30-6.png",
    "image": "/robots/vibe-vibers-bureau-roll-30-6.png",
    "name": "BUREAU 30-6",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 35,
      "speed": 77,
      "spark": 65
    },
    "source": "file-derived"
  },
  {
    "id": "055",
    "number": 55,
    "file": "vibe-vibers-bureau-roll-30-10.png",
    "image": "/robots/vibe-vibers-bureau-roll-30-10.png",
    "name": "BUREAU 30-10",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 41,
      "speed": 82,
      "spark": 58
    },
    "source": "file-derived"
  },
  {
    "id": "056",
    "number": 56,
    "file": "vibe-vibers-bureau-roll-31-4.png",
    "image": "/robots/vibe-vibers-bureau-roll-31-4.png",
    "name": "BUREAU 31-4",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 60,
      "speed": 65,
      "spark": 36
    },
    "source": "file-derived"
  },
  {
    "id": "057",
    "number": 57,
    "file": "vibe-vibers-bureau-roll-31-11.png",
    "image": "/robots/vibe-vibers-bureau-roll-31-11.png",
    "name": "BUREAU 31-11",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 86,
      "speed": 71,
      "spark": 46
    },
    "source": "file-derived"
  },
  {
    "id": "058",
    "number": 58,
    "file": "vibe-vibers-bureau-roll-32-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-32-3.png",
    "name": "BUREAU 32-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "legendary",
    "stats": {
      "power": 52,
      "speed": 31,
      "spark": 35
    },
    "source": "file-derived"
  },
  {
    "id": "059",
    "number": 59,
    "file": "vibe-vibers-bureau-roll-32-7.png",
    "image": "/robots/vibe-vibers-bureau-roll-32-7.png",
    "name": "BUREAU 32-7",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 34,
      "speed": 69,
      "spark": 90
    },
    "source": "file-derived"
  },
  {
    "id": "060",
    "number": 60,
    "file": "vibe-vibers-bureau-roll-33-4.png",
    "image": "/robots/vibe-vibers-bureau-roll-33-4.png",
    "name": "BUREAU 33-4",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 70,
      "speed": 91,
      "spark": 61
    },
    "source": "file-derived"
  },
  {
    "id": "061",
    "number": 61,
    "file": "vibe-vibers-bureau-roll-33-5.png",
    "image": "/robots/vibe-vibers-bureau-roll-33-5.png",
    "name": "BUREAU 33-5",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 54,
      "speed": 92,
      "spark": 69
    },
    "source": "file-derived"
  },
  {
    "id": "062",
    "number": 62,
    "file": "vibe-vibers-bureau-roll-35-4.png",
    "image": "/robots/vibe-vibers-bureau-roll-35-4.png",
    "name": "BUREAU 35-4",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "rare",
    "stats": {
      "power": 91,
      "speed": 44,
      "spark": 62
    },
    "source": "file-derived"
  },
  {
    "id": "063",
    "number": 63,
    "file": "vibe-vibers-bureau-roll-35-5.png",
    "image": "/robots/vibe-vibers-bureau-roll-35-5.png",
    "name": "BUREAU 35-5",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 74,
      "speed": 37,
      "spark": 69
    },
    "source": "file-derived"
  },
  {
    "id": "064",
    "number": 64,
    "file": "vibe-vibers-bureau-roll-35-6.png",
    "image": "/robots/vibe-vibers-bureau-roll-35-6.png",
    "name": "BUREAU 35-6",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "epic",
    "stats": {
      "power": 33,
      "speed": 76,
      "spark": 81
    },
    "source": "file-derived"
  },
  {
    "id": "065",
    "number": 65,
    "file": "vibe-vibers-bureau-roll-36-1.png",
    "image": "/robots/vibe-vibers-bureau-roll-36-1.png",
    "name": "BUREAU 36-1",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "epic",
    "stats": {
      "power": 66,
      "speed": 46,
      "spark": 54
    },
    "source": "file-derived"
  },
  {
    "id": "066",
    "number": 66,
    "file": "vibe-vibers-bureau-roll-36-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-36-3.png",
    "name": "BUREAU 36-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "rare",
    "stats": {
      "power": 66,
      "speed": 58,
      "spark": 81
    },
    "source": "file-derived"
  },
  {
    "id": "067",
    "number": 67,
    "file": "vibe-vibers-bureau-roll-37-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-37-3.png",
    "name": "BUREAU 37-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 67,
      "speed": 93,
      "spark": 89
    },
    "source": "file-derived"
  },
  {
    "id": "068",
    "number": 68,
    "file": "vibe-vibers-bureau-roll-38-5.png",
    "image": "/robots/vibe-vibers-bureau-roll-38-5.png",
    "name": "BUREAU 38-5",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 75,
      "speed": 66,
      "spark": 66
    },
    "source": "file-derived"
  },
  {
    "id": "069",
    "number": 69,
    "file": "vibe-vibers-bureau-roll-38-11.png",
    "image": "/robots/vibe-vibers-bureau-roll-38-11.png",
    "name": "BUREAU 38-11",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 92,
      "speed": 48,
      "spark": 46
    },
    "source": "file-derived"
  },
  {
    "id": "070",
    "number": 70,
    "file": "vibe-vibers-bureau-roll-40-10.png",
    "image": "/robots/vibe-vibers-bureau-roll-40-10.png",
    "name": "BUREAU 40-10",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 56,
      "speed": 99,
      "spark": 60
    },
    "source": "file-derived"
  },
  {
    "id": "071",
    "number": 71,
    "file": "vibe-vibers-bureau-roll-42-8.png",
    "image": "/robots/vibe-vibers-bureau-roll-42-8.png",
    "name": "BUREAU 42-8",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 69,
      "speed": 83,
      "spark": 91
    },
    "source": "file-derived"
  },
  {
    "id": "072",
    "number": 72,
    "file": "vibe-vibers-bureau-roll-43-2.png",
    "image": "/robots/vibe-vibers-bureau-roll-43-2.png",
    "name": "BUREAU 43-2",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "legendary",
    "stats": {
      "power": 80,
      "speed": 100,
      "spark": 31
    },
    "source": "file-derived"
  },
  {
    "id": "073",
    "number": 73,
    "file": "vibe-vibers-bureau-roll-45-3.png",
    "image": "/robots/vibe-vibers-bureau-roll-45-3.png",
    "name": "BUREAU 45-3",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 35,
      "speed": 76,
      "spark": 84
    },
    "source": "file-derived"
  },
  {
    "id": "074",
    "number": 74,
    "file": "vibe-vibers-bureau-roll-45-9.png",
    "image": "/robots/vibe-vibers-bureau-roll-45-9.png",
    "name": "BUREAU 45-9",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "uncommon",
    "stats": {
      "power": 89,
      "speed": 62,
      "spark": 54
    },
    "source": "file-derived"
  },
  {
    "id": "075",
    "number": 75,
    "file": "vibe-vibers-bureau-roll-46-12.png",
    "image": "/robots/vibe-vibers-bureau-roll-46-12.png",
    "name": "BUREAU 46-12",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "rare",
    "stats": {
      "power": 66,
      "speed": 39,
      "spark": 42
    },
    "source": "file-derived"
  },
  {
    "id": "076",
    "number": 76,
    "file": "vibe-vibers-bureau-roll-47-10 (1).png",
    "image": "/robots/vibe-vibers-bureau-roll-47-10 (1).png",
    "name": "BUREAU 47-10 (1)",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 65,
      "speed": 52,
      "spark": 69
    },
    "source": "file-derived"
  },
  {
    "id": "077",
    "number": 77,
    "file": "vibe-vibers-bureau-roll-48-6.png",
    "image": "/robots/vibe-vibers-bureau-roll-48-6.png",
    "name": "BUREAU 48-6",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 34,
      "speed": 85,
      "spark": 37
    },
    "source": "file-derived"
  },
  {
    "id": "078",
    "number": 78,
    "file": "vibe-vibers-bureau-roll-48-7.png",
    "image": "/robots/vibe-vibers-bureau-roll-48-7.png",
    "name": "BUREAU 48-7",
    "description": null,
    "series": "BUREAU ROLL",
    "rarity": "common",
    "stats": {
      "power": 72,
      "speed": 66,
      "spark": 78
    },
    "source": "file-derived"
  },
  {
    "id": "079",
    "number": 79,
    "file": "vibe-vibers-viber-6.png",
    "image": "/robots/vibe-vibers-viber-6.png",
    "name": "VIBERS 06",
    "description": "Brown Viber with little mint eyes and twin antennas",
    "series": "VIBERS",
    "rarity": "rare",
    "stats": {
      "power": 51,
      "speed": 41,
      "spark": 61
    },
    "source": "official:vibevibe"
  },
  {
    "id": "080",
    "number": 80,
    "file": "vibe-vibers-viber-10.png",
    "image": "/robots/vibe-vibers-viber-10.png",
    "name": "VIBERS 10",
    "description": "Green Viber with a cap and oversized turquoise glasses",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 76,
      "speed": 82,
      "spark": 70
    },
    "source": "official:vibevibe"
  },
  {
    "id": "081",
    "number": 81,
    "file": "vibe-vibers-viber-31.png",
    "image": "/robots/vibe-vibers-viber-31.png",
    "name": "VIBERS 31",
    "description": "Red Viber with a tall block mohawk",
    "series": "VIBERS",
    "rarity": "uncommon",
    "stats": {
      "power": 53,
      "speed": 67,
      "spark": 33
    },
    "source": "official:vibevibe"
  },
  {
    "id": "082",
    "number": 82,
    "file": "vibe-vibers-viber-32.png",
    "image": "/robots/vibe-vibers-viber-32.png",
    "name": "VIBERS 32",
    "description": "Silver Viber with orange antennas and orange boots",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 68,
      "speed": 58,
      "spark": 40
    },
    "source": "official:vibevibe"
  },
  {
    "id": "083",
    "number": 83,
    "file": "vibe-vibers-viber-42.png",
    "image": "/robots/vibe-vibers-viber-42.png",
    "name": "VIBERS 42",
    "description": "Orange Viber with a green hat and turquoise eyes",
    "series": "VIBERS",
    "rarity": "uncommon",
    "stats": {
      "power": 47,
      "speed": 40,
      "spark": 73
    },
    "source": "official:vibevibe"
  },
  {
    "id": "084",
    "number": 84,
    "file": "vibe-vibers-viber-48.png",
    "image": "/robots/vibe-vibers-viber-48.png",
    "name": "VIBERS 48",
    "description": "Teal Viber with a propeller hat and mint glasses",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 33,
      "speed": 90,
      "spark": 36
    },
    "source": "official:vibevibe"
  },
  {
    "id": "085",
    "number": 85,
    "file": "vibe-vibers-viber-63.png",
    "image": "/robots/vibe-vibers-viber-63.png",
    "name": "VIBERS 63",
    "description": "Brown Viber with purple glasses and a red mohawk",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 68,
      "speed": 57,
      "spark": 33
    },
    "source": "official:vibevibe"
  },
  {
    "id": "086",
    "number": 86,
    "file": "vibe-vibers-viber-71.png",
    "image": "/robots/vibe-vibers-viber-71.png",
    "name": "VIBERS 71",
    "description": "Brown pirate Viber with an eye patch",
    "series": "VIBERS",
    "rarity": "rare",
    "stats": {
      "power": 91,
      "speed": 30,
      "spark": 84
    },
    "source": "official:vibevibe"
  },
  {
    "id": "087",
    "number": 87,
    "file": "vibe-vibers-viber-84.png",
    "image": "/robots/vibe-vibers-viber-84.png",
    "name": "VIBERS 84",
    "description": "Cream Viber with a red cap and red eyebrows",
    "series": "VIBERS",
    "rarity": "uncommon",
    "stats": {
      "power": 87,
      "speed": 52,
      "spark": 87
    },
    "source": "official:vibevibe"
  },
  {
    "id": "088",
    "number": 88,
    "file": "vibe-vibers-viber-103.png",
    "image": "/robots/vibe-vibers-viber-103.png",
    "name": "VIBERS 103",
    "description": "Gold-toned Viber with twin antennas and a striped chest",
    "series": "VIBERS",
    "rarity": "uncommon",
    "stats": {
      "power": 74,
      "speed": 100,
      "spark": 55
    },
    "source": "official:vibevibe"
  },
  {
    "id": "089",
    "number": 89,
    "file": "vibe-vibers-viber-123.png",
    "image": "/robots/vibe-vibers-viber-123.png",
    "name": "VIBERS 123",
    "description": "Purple Viber with a white cap and blue eyes",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 41,
      "speed": 91,
      "spark": 40
    },
    "source": "official:vibevibe"
  },
  {
    "id": "090",
    "number": 90,
    "file": "vibe-vibers-viber-141.png",
    "image": "/robots/vibe-vibers-viber-141.png",
    "name": "VIBERS 141",
    "description": "Dark Viber with a silver fedora and green glasses",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 47,
      "speed": 81,
      "spark": 47
    },
    "source": "official:vibevibe"
  },
  {
    "id": "091",
    "number": 91,
    "file": "vibe-vibers-viber-142.png",
    "image": "/robots/vibe-vibers-viber-142.png",
    "name": "VIBERS 142",
    "description": "Copper Viber with a brown fedora and coral eyes",
    "series": "VIBERS",
    "rarity": "common",
    "stats": {
      "power": 48,
      "speed": 92,
      "spark": 95
    },
    "source": "official:vibevibe"
  },
  {
    "id": "092",
    "number": 92,
    "file": "vibe-vibers-viber-extra-9.png",
    "image": "/robots/vibe-vibers-viber-extra-9.png",
    "name": "VIBER EXTRAS 09",
    "description": "Blue Viber with a brown hat and glowing gold eyes",
    "series": "VIBER EXTRAS",
    "rarity": "common",
    "stats": {
      "power": 77,
      "speed": 46,
      "spark": 30
    },
    "source": "official:vibevibe"
  },
  {
    "id": "093",
    "number": 93,
    "file": "vibe-vibers-viber-extra-11.png",
    "image": "/robots/vibe-vibers-viber-extra-11.png",
    "name": "VIBER EXTRAS 11",
    "description": "Brown Viber with glowing lime glasses and a red mouth",
    "series": "VIBER EXTRAS",
    "rarity": "uncommon",
    "stats": {
      "power": 77,
      "speed": 53,
      "spark": 90
    },
    "source": "official:vibevibe"
  },
  {
    "id": "094",
    "number": 94,
    "file": "vibe-vibers-viber-extra-12.png",
    "image": "/robots/vibe-vibers-viber-extra-12.png",
    "name": "VIBER EXTRAS 12",
    "description": "Gold-toned Viber with glowing yellow eyes and a side antenna",
    "series": "VIBER EXTRAS",
    "rarity": "rare",
    "stats": {
      "power": 63,
      "speed": 60,
      "spark": 50
    },
    "source": "official:vibevibe"
  },
  {
    "id": "095",
    "number": 95,
    "file": "vibe-vibers-viber-extra-15.png",
    "image": "/robots/vibe-vibers-viber-extra-15.png",
    "name": "VIBER EXTRAS 15",
    "description": "Transparent turquoise Viber with a square smile",
    "series": "VIBER EXTRAS",
    "rarity": "common",
    "stats": {
      "power": 94,
      "speed": 47,
      "spark": 40
    },
    "source": "official:vibevibe"
  },
  {
    "id": "096",
    "number": 96,
    "file": "vibe-vibers-viber-extra-19.png",
    "image": "/robots/vibe-vibers-viber-extra-19.png",
    "name": "VIBER EXTRAS 19",
    "description": "Brown Viber with a black top hat and a blue hatband",
    "series": "VIBER EXTRAS",
    "rarity": "common",
    "stats": {
      "power": 82,
      "speed": 73,
      "spark": 97
    },
    "source": "official:vibevibe"
  },
  {
    "id": "097",
    "number": 97,
    "file": "vibe-vibers-viber-extra-20.png",
    "image": "/robots/vibe-vibers-viber-extra-20.png",
    "name": "VIBER EXTRAS 20",
    "description": "Sand-colored Viber with a red mohawk and red boots",
    "series": "VIBER EXTRAS",
    "rarity": "common",
    "stats": {
      "power": 83,
      "speed": 94,
      "spark": 79
    },
    "source": "official:vibevibe"
  },
  {
    "id": "098",
    "number": 98,
    "file": "vibe-vibers-viber-extra-24.png",
    "image": "/robots/vibe-vibers-viber-extra-24.png",
    "name": "VIBER EXTRAS 24",
    "description": "Brown Viber with a white fedora and glowing gold eyes",
    "series": "VIBER EXTRAS",
    "rarity": "common",
    "stats": {
      "power": 55,
      "speed": 57,
      "spark": 84
    },
    "source": "official:vibevibe"
  }
];

export const TOTAL_CARDS = CARDS.length;
